services:
  patreon-plex:
    image: ghcr.io/terjefl/patreon-plex:latest
    container_name: patreon-plex
    restart: unless-stopped
    ports:
      - "8400:8000"   # index page
    environment:
      - TZ=Europe/Oslo
    volumes:
      - ./config:/config:ro    # config.yaml + cookies.txt
      - ./data:/data
      - /path/to/media/Patreon:/library
